name: hcv-nf
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - pandas=1.3.5
  - spades=3.15.3
  - blast=2.12.0
  - bwa=0.7.17
  - samtools=1.14
  - qualimap=2.2.2d
  - bcftools=1.14
  - bedtools=2.30.0
  - seqtk=1.3
  - seqkit=2.2.0
  - perl-digest-sha=5.88
  - fastp=0.23.1
  - multiqc=1.12
  - perl-list-moreutils=0.430
  - mafft=7.508
  - raxml=8.2.12
  - cutadapt=4.1
  - bbmap=38.98
  - taxonkit=0.14.2